### PR TITLE
prototype

### PR DESCRIPTION
**Pull request by plandem**
here is prototype. it's quite hard to collaborate  for go projects, or i don't know how. Can you revise it?

### CODE REVIEW

**Comment by sturgill** [comment]
This is a pretty good first stab; thanks for getting this started. The more I think about this, the more I think `data.Payload` should be an interface with methods:
- `Bytes() []byte`
- `Parse() (interface{}, error)`
- `ParseSilent() (interface{}, error)`
- `Objects() ([]map[string]interface{}, error)`

See [data.JSON](https://github.com/dailyburn/ratchet/blob/develop/data/json.go) for the general approach.

That would allow us to use whatever `data.Payload` the user defines across all processors (including our stock output processors). We'll update `data.JSON` as the working example. The only downside is that this would be a breaking change, but I'm not as concerned about that (mostly because I think it's the best way forward).

Thoughts?

**Comment by sturgill** [comment]
Actually, `Bytes() []byte` might not even be needed. As long as the `data.Payload` can be parsed, we shouldn't really care how someone decides to embed the data itself.

**Comment by plandem** [comment]
I thought about more generic interface, but in that case we will need to know how to clone payloads at **branchOut**, or we will have alot of reflection, that probably not the fastest thing.

I used **clone** at first commit, but removed it lately.

**Comment by sturgill** [comment]
The interface could also require a `Clone() data.Payload` method. And we leave it up to the user to do what's best given how they decide to store data internally.

**Comment by plandem** [comment]
in that case it will solve everything. will try to refactor tomorrow.

**Comment by stephenb** [comment]
Hey fellas, I've been following along on this thread. I think this is a great idea.

One thought: could this complicate DataProcessor logic? Right now SQL and CSV type processors have some expected logic around the JSON input. Or, is the idea`Objects()` would provide the basis for this type of logic moving forward (in which case this change makes even more sense to me).

**Comment by sturgill** [comment]
In my mind we move all logic to Parse and Objects. And let the payload define how to get things out.

**Comment by sturgill** [comment]
Things like the stock SQLReader (not dynamic) will probably need to just use some default for simplicity (JSON or otherwise), but it can be easily put into any other data structure in a transformer for future processing. Dynamic SQL reader will return the user's defined payload type. 

But that seems like a solid trade off.

**Comment by stephenb** [comment]
Cool. Maybe something less JSONy than Parse() and Objects()? Does Serialize() and Deserialize() make more sense?

**Comment by plandem** [comment]
in that case it's just common **encoding** with built-in ** BinaryMarshaler/BinaryUnmarshaler** interface

**Comment by plandem** [comment]
i have the only question....
```
func ObjectsFromJSON(d JSON) ([]map[string]interface{}, error)
```
why **[]map[string]interface{}**, why not []Payload?

**Pull request closed without merging**
